# Generated by Django 3.0.2 on 2022-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
