# Generated by Django 3.0.2 on 2022-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahidapp', '0002_counter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
